## Numpy is also called as Numerical Python used to perform various numerical and scientific computing in Python. Let us have a look at various mathematical functions, that are essential for data science, machine learning, engineering, and more.

Importing Numpy Package

In [4]:
import numpy as np

Numpy is used to create various array operations like  creating an NumPy array from a Python list or tuple.

In [6]:
a = np.array([1, 2, 3, 4, 5])  # 1D array
b = np.array([(1, 2, 3), (4, 5, 6)])  # 2D array
print(a)
print(b)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


Numpy can be used to initialize arrays with specific values like zeros and ones or any other matrices for linear algebra operations. 

In [10]:
zero_matrix = np.zeros((2, 3))  
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
ones_matrix = np.ones((2, 2), dtype=int)
print (ones_matrix)

[[1 1]
 [1 1]]


We can create sequences of numbers using Numpy for numerical computing.

In [23]:
# Syntax : np.arange(start, stop, step size)

range = np.arange(1, 11, 2) 
print (range)


[1 3 5 7 9]


NumPy's product function is used to perform Matrix multiplication for 2D arrays.

In [2]:
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])
dot_product = np.dot(c, d)
print(dot_product)

NameError: name 'np' is not defined

NumPy's built-in statistical functions allow for easy computation of key statistical measures, facilitating robust data analysis and interpretation.

In [28]:
stats = np.array([1, 2, 3, 4, 5])
mean_val = np.mean(stats)
median_val = np.median(stats)
std_val = np.std(stats)
print(mean_val)
print(median_val)
print(std_val)

3.0
3.0
1.4142135623730951


NumPy’s random submodule offers a wide range of functions to generate random numbers from various distributions, which is used to create stochastic models and performing Monte Carlo simulations.

In [31]:
n = np.random.rand(2, 3)
print(n)

[[0.82974812 0.92313289 0.1281779 ]
 [0.69377248 0.79893395 0.07256955]]


Numpy's help guide

In [34]:
 np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
